name: ebook_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-117.0.dev <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  cached_network_image: ^3.2.3
  custom_navigation_bar: ^0.8.2
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.8.4
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.0
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  page_transition: ^2.0.9
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GTSectraFineRegular.ttf
