name: ebook_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-117.0.dev <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.9.1
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.8.4
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.0
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  html: ^0.15.4
  image: ^4.0.17
  intl: ^0.18.1
  lottie: ^2.6.0
  page_transition: ^2.0.9
  palette_generator: ^0.3.3+3
  skeletonizer: ^0.7.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  change_app_package_name: ^1.1.0

flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/images/play_store_512.png"
    adaptive_icon_foreground: "assets/images/play_store_512.png"
    adaptive_icon_background: "#ffffff"

    
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GTSectraFineRegular.ttf
